String style =
"<style>"
"label {"
"  margin: 5px;"
"}"
"#file-input, input {"
"  width: 100%;"
"  height: 44px;"
"  border-radius: 4px;"
"  margin: 10px auto;"
"  font-size: 15px;"
"}"
"input {"
"  background: #f1f1f1;"
"  border: 0;"
"  padding: 0 10px;"
"}"
"body {"
"  font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;"
"  font-size: 14px;"
"  color: #777;"
"}"
"html {"
"  background: no-repeat linear-gradient(45deg, #808, #088);"
"  width: 100%;"
"  height: 100%;"
"  font-weight: bold;"
"}"
".emoji {"
"  font-family: apple color emoji,segoe ui emoji,noto color emoji,android emoji,emojisymbols,emojione mozilla,twemoji mozilla,segoe ui symbol;"
"}"
"#file-input {"
"  padding: 0;"
"  border: 1px solid #ddd;"
"  line-height: 44px;"
"  text-align: center;"
"  display: block;"
"  cursor: pointer;"
"  color: purple;"
"}"
"#bar, #prgbar {"
"  background-color: #f1f1f1;"
"  border-radius: 10px"
"}"
"#bar {"
"  background: linear-gradient(90deg, #808, #088);"
"  width: 0%;"
"  height: 1em;"
"}"
"form {"
"  background: #fff;"
"  max-width: 258px;"
"  margin: 75px auto;"
"  padding: 30px;"
"  border-radius: 10px;"
"}"
".btn {"
"  background: no-repeat linear-gradient(90deg, #ff0040, #800080);"
"  color: #fff;"
"  cursor: pointer;"
"}"
"h1 {"
"  background: no-repeat linear-gradient(45deg, #808, #088);"
"  -webkit-background-clip: text;"
"  -webkit-text-fill-color: transparent;"
"  font-size: 4em;"
"}"
".homebtn {"
"  padding: 10px;"
"  border: 0;"
"  width: 100%;"
"  height: 44px;"
"  border-radius: 4px;"
"  margin: 10px auto;"
"  font-size: 15px;"
"  background: #eee;"
"  color: purple;"
"}"
"</style>";

String loginIndex = 
"<!doctype html>"
"<html>"
"<head>"
"<title>ESP32 OTA Login</title>"
"<meta name=\"robots\" content=\"noindex, nofollow, noarchive\" />"
"</head>"
"<body>"
"<form name=loginForm onsubmit='return false;'>"
"<h1>ESP32 Login</h1>"
"<input name=userid placeholder='User ID'> "
"<input name=pwd placeholder=Password type=Password> "
"<input type=submit onclick='check(this.form)' class=btn value=Login></form>"
"<script>"
"function check(form) {"
"if (form.userid.value == form.pwd.value && form.userid.value == ['p','r','o','g','r','a','m'].join('')) {"
"window.location.href = '/server' + 'Index'"
"} else {"
"alert('Nope. This is MY ESP32.');"
"}"
"}"
"</script>"
"" + style +
"</body>"
"</html>";
String serverIndex = "<!doctype html>"
"<head>"
"<title>ESP32 firmware upload</title>"
"<meta name=\"robots\" content=\"noindex, nofollow, noarchive\" />"
"</head>"
"<body>"
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
"<button onclick='window.location.href = \"/\";' class='btn homebtn'>Go home</button>"
"<input type='file' name='update' id='file' onchange='sub(this)' style=display:none accept='.bin'>"
"<label id='file-input' for='file'>Choose file</label>"
"<input type='submit' class=btn value='Upload'>"
"<br><br>"
"<div id='prg'>Nothing uploaded</div>"
"<br><div id='prgbar'><div id='bar'></div></div><br>"
"<script>"
"function sub(obj){"
"var fileName = obj.value.split('\\\\');"
"document.getElementById('file-input').innerHTML = '   ' + fileName[fileName.length-1];"
"};"
"$('form').submit(function(e){"
"e.preventDefault();"
"var form = $('#upload_form')[0];"
"var data = new FormData(form);"
"$.ajax({"
"url: '/update',"
"type: 'POST',"
"data: data,"
"contentType: false,"
"processData:false,"
"xhr: function() {"
"var xhr = new window.XMLHttpRequest();"
"xhr.upload.addEventListener('progress', function(evt) {"
"if (evt.lengthComputable) {"
"var per = evt.loaded / evt.total;"
"$('#prg').html('Progress: ' + Math.round(per*100) + '%');"
"$('#bar').css('width',Math.round(per*100) + '%');"
"if (per == 1) {"
"$('#prg').html('Done! <span class=\\'emoji\\'>&#10004;</span>');"
"}"
"}"
"}, false);"
"return xhr;"
"},"
"success:function(d, s) {"
"console.log('success!') "
"},"
"error: function (a, b, c) {"
"}"
"});"
"});"
"function activityWatcher(){"
"var secondsSinceLastActivity = 0;"
"var maxInactivity = (60 * 2);"
"setInterval(function(){"
"secondsSinceLastActivity++;"
"if(secondsSinceLastActivity > maxInactivity){"
"location.href = '/';"
"}"
"}, 1000);"
"function activity(){"
"        secondsSinceLastActivity = 0;"
"}"
"var activityEvents = ['mousedown', 'mousemove', 'keydown', 'scroll', 'touchstart'];"
"activityEvents.forEach(function(eventName) {"
"document.addEventListener(eventName, activity, true);"
"});"
"}"
"activityWatcher();"
"</script>"
"" + style +
"</body>"
"</html>";
